before_install:
    - npm install -g grunt-cli
    - npm install -g bower
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
    - npm install
    - bower install -f
language: node_js
node_js:
    - "4.1"
